authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

elearning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.urls.conf import re_path
from quiz.views import home as home_view

urlpatterns = [
    path('student/', include('quiz.urls')),
    path('auth/', include('authentication.urls')),
    path('admin/', admin.site.urls),
] \
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+[
    re_path(r'.*', home_view)
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('categories/<int:category_id>/answer-question', views.AnswerQuestionView.as_view(), name='answer_question'),
]

templates/site/partials/header.html
{% load static %}

<nav class="flex items-center justify-between flex-wrap text-white bg-sky-600 p-6 pl-10 gap-10">
  <div class="flex items-center flex-no-shrink text-white mr-6">
    <img class="w-7 h-7 mr-2" src="{% static 'images/brand-logo.png'%}">
    <span class="font-semibold text-neutral-900 text-xl tracking-tight">E-Learning</span>
  </div>
  <div class="block md:hidden">
    <button id="header-menu-button"
      class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
      <svg class="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <title>Menu</title>
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
      </svg>
    </button>
  </div>
  {% if user.is_authenticated %}

  <div class="w-full block flex-grow md:flex md:items-center md:w-auto">
    <div class="text-sm md:flex-grow">
      <a href="{% url 'quiz:category_list' %}" class="hover:opacity-70 block mt-4 font-bold md:inline-block md:mt-0 mr-4">
        Categories
      </a>
    </div>
    <div class="lg:flex-grow lg:flex lg:justify-end">
      <a href="{% url 'authentication:logout' %}" class="hover:opacity-70 block mt-4 font-bold lg:inline-block lg:mt-0 mr-4">
        <span class="text-right">Logout</span>
        <span class="ml-2"><i class="fas fa-sign-out-alt"></i></span>
      </a>
    </div>
  </div>
  {% else %}
  <div class="w-full hidden text-center md:flex-grow md:flex md:justify-end md:items-center md:w-auto"
    id="header-menu">
    <div class="text-sm hover:text-white">
      <a href="{% url 'authentication:login' %}" class="block mt-4 font-bold md:inline-block md:mt-0  mr-4">
        Login
      </a>
    </div>
    <div class="text-sm hover:text-white">
      <a href="{% url 'authentication:register' %}" class="block mt-4 font-bold md:inline-block md:mt-0  mr-4">
        Sign-up
      </a>
    </div>
  </div>
  {% endif %}

</nav>